### ISSUE TITLE
Update Cocoapods

### ISSUE THREAD

**Issue by rsanchezsaez** [jpsim/JPSVolumeButtonHandler#10]
It would be great to update the version found in Cocoapods to include the latest changes.

**Comment by sraposa** [comment]
I vote for the same. I'm relatively new to Cocoapods -- didn't realize that it wouldn't automatically pull the latest Master commit. Took me an hour to figure out why I wasn't seeing all the great new changes.  :(

**Comment by jpsim** [comment]
I just tagged 1.0.0 from master and updated CocoaPods. Thanks for the request!

**Comment by sraposa** [comment]
Perfect. And thanks for your work on the library!
