### ISSUE TITLE
Calling startHandler:

### ISSUE THREAD

**Issue by apple-ihack-geek** [jpsim/JPSVolumeButtonHandler#35]
What is supposed to call startHandler:? 
If we are supposed to do that in our code, mind if I make a RP to amend the readme to let people know to do so ?

**Comment by samyes** [comment]
(I added startHandler recently to enable the ability to start and stop an existing handler)
Yes, that would be great, thank you!

**Comment by apple-ihack-geek** [comment]
JP merged before I got a chance to fix it, but nbd.  Thanks all for this great project, really saved me a bunch of time.
