### ISSUE TITLE
Music stops when app starts and sets buttonHandler

### ISSUE THREAD

**Issue by kronik** [jpsim/JPSVolumeButtonHandler#39]
Music stops when app starts and sets buttonHandler. Figured out that session category is set incorrectly. Tried with AVAudioSessionCategoryAmbient and music works fine now.

**Comment by jpsim** [comment]
We used to have `AVAudioSessionCategoryAmbient`, but that was changed to `Playback` in #22 and again to `PlayAndRecord` in #32. See those PRs for the motivations why we changed this.

However, maybe it would be worth exposing a way for users to specify which mode to use?

**Comment by kronik** [comment]
@jpsim Exposing it as a property (or a constructor parameter) sounds really good.

**Comment by kronik** [comment]
Added a [PR](https://github.com/jpsim/JPSVolumeButtonHandler/pull/40)

**Comment by kronik** [comment]
@jpsim any thoughts on PR?

**Comment by jpsim** [comment]
Merged.
