### ISSUE TITLE
using deprecated method setVolume: 

### ISSUE THREAD

**Issue by dermaaarkus** [jpsim/JPSVolumeButtonHandler#4]
[[MPMusicPlayerController applicationMusicPlayer] setVolume:(float)volume]; is deprecated and we don't know when apple will remove it.
i think there is currently no alternative, but maybe this could be solved in future?
thanks for this nice class

**Comment by jpsim** [comment]
I'm also unaware of a better alternative, so we'll keep as-is until we have other options.

**Comment by dirkmcpherson** [comment]
Do you know if apps are accepted into the iOS store using this class? 

It's very useful, thanks for building it.

**Comment by jpsim** [comment]
> Do you know if apps are accepted into the iOS store using this class?

Yes, there are apps on the App Store using this library.
