### ISSUE TITLE
Initialization prevents bluetooth audio playback

### ISSUE THREAD

**Issue by apple-ihack-geek** [jpsim/JPSVolumeButtonHandler#46]
Whenever I start JPSVolumeButtonHandler, sadly bluetooth audio playback stops.  I tried setting the option for "AVAudioSessionCategoryOptionAllowBluetooth" but sadly it made no difference.  Any idea how best to resolve this?
Thanks.

**Comment by CallumOz** [comment]
Same problem here. Using version 1.0.1, I had no problems.
I have reverted to this older version for the time being.

**Comment by jpsim** [comment]
There's a larger problem here where I'm not actively maintaining this library, I've just been merging PRs and pushing releases.

So I depend on contributors filing PRs to be diligent in preventing compatibility issues with previous versions, but no one (myself included) has really taken the responsibility of ensuring this library remains high quality.

I'd like to invite any active users interested in helping maintain, or even take over, this library to please let me know. It's obviously a library that's still somewhat actively used, so it deserves a bit of regular maintenance love and care 😄

**Comment by apple-ihack-geek** [comment]
@CallumOz This should fix our issues. 
@jpsim I can help review people's PRs, but someone should be reviewing mine too (since I've been on a roll lately ;) ) , so maybe add me and one other person, make master branch protected, and then that way at least one of the three of us has to approve.

**Comment by CallumOz** [comment]
Thanks for the hard work @apple-ihack-geek!
It works great during audio playback to a bluetooth device.
However the handler's aren't called during Bluetooth streaming, and the volume buttons change the Bluetooth audio volume instead.
In version 1.0.1, the handlers are called even when streaming Bluetooth audio and don't change the volume.

I'm not complaining, I'm juste wondering what has changed.
