### ISSUE TITLE
New release for Xcode9 warnings?

### ISSUE THREAD

**Issue by mrgrauel** [jpsim/JPSVolumeButtonHandler#50]
Do you plan to create a new version tonight?

**Comment by jpsim** [comment]
Can you be more specific about the warnings you're seeing?

Creating a project importing these source files with Xcode 9 beta 6 doesn't present any warnings:

![image](https://user-images.githubusercontent.com/474794/30337146-40b9ede6-979c-11e7-8982-42168776fe9d.png)

**Comment by mrgrauel** [comment]
No I just mean that you officially tag a new version, that we do not have to point to the git repo.

**Comment by jpsim** [comment]
Ah, I see. Done.
