### ISSUE TITLE
Install Via SPM?

### ISSUE THREAD

**Issue by thoughtcastapp** [jpsim/JPSVolumeButtonHandler#66]
Is it possible to install this repo via spm and not cocoapods?

**Comment by nylki** [comment]
I just created PR, that would add SPM support: https://github.com/jpsim/JPSVolumeButtonHandler/pull/67.
@thoughtcastapp feel free to test! 🙂

**Comment by thoughtcastapp** [comment]
@nylki looks like this is working, should be safe to merge hopefully...ty for this!

**Comment by thoughtcastapp** [comment]
@nylki looks like it is working :) thank you again!

**Comment by jpsim** [comment]
Thanks both.
